#!/bin/bash
# gen_key_source.sh -- emit PolishModelKey.generated.swift from the key file.
#
# The polish model's AES key has to be inside the shipped binary; that is the
# whole design (see package_model.py -- it is a speed bump, not a boundary).
# What it must not be is *in git*, where it would outlive any rotation and sit
# in history forever. So it is generated at build time from a file that lives
# outside the repo, and the generated source is gitignored.
#
# Wired into the whisperer target as the "Generate polish model key" run-script
# phase, ahead of Compile Sources. User script sandboxing is on, so the phase
# declares both the key file and the generated source as input/output paths --
# without those the sandbox denies reading even this script.
#
# On a *fresh clone* run it once by hand before the first build. `Whisperer/` is
# a file-system-synchronized group, which Xcode scans when it opens the project;
# a generated file that does not exist at scan time is not in Compile Sources for
# that build, no matter how early the phase runs.
#
#     Tools/mmbert/gen_key_source.sh

set -euo pipefail

KEY_FILE="${WHISPERER_MODEL_KEY_FILE:-$HOME/.whisperer-model-key}"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/Whisperer/Transcription/Editing/PolishModelKey.generated.swift"

if [ ! -f "$KEY_FILE" ]; then
    echo "error: no key at $KEY_FILE -- run Tools/mmbert/package_model.py first" >&2
    exit 1
fi

KEY="$(tr -d '[:space:]' < "$KEY_FILE")"
if [ "${#KEY}" -ne 64 ]; then
    echo "error: $KEY_FILE is ${#KEY} hex chars, expected 64" >&2
    exit 1
fi

NEW="$(cat <<EOF
// Generated by Tools/mmbert/gen_key_source.sh. Do not edit, do not commit.
// Regenerate after any rotation of ~/.whisperer-model-key.

import Foundation

enum PolishModelKey {
    /// Hex-encoded AES-256 key for the polish model package.
    static let hex = "$KEY"
}
EOF
)"

# Only rewrite when the contents change, so an unchanged key does not invalidate
# the build's incremental-compile cache on every launch.
if [ -f "$OUT" ] && [ "$(cat "$OUT")" = "$NEW" ]; then
    exit 0
fi
printf '%s\n' "$NEW" > "$OUT"
echo "wrote $OUT"
