//
//  MeetingAIService.swift
//  Whisperer
//
//  LLM-powered meeting overview generation and RAG-based Q&A.
//  ask() retrieves the top-8 semantically relevant chunks from the
//  Wax index before calling the LLM — much faster and more accurate
//  than dumping the full transcript.
//

import Foundation

// MARK: - Answer model

struct RAGAnswer {
    let text: String
    let sources: [RAGChunk]   // chunks fed to the LLM (empty when falling back)
    let usedRAG: Bool
}

// MARK: - Service

actor MeetingAIService {
    static let shared = MeetingAIService()

    private init() {}

    // MARK: - RAG indexing

    /// Index (or re-index) a meeting's segments into Wax. Safe to call from
    /// a background Task — failures are logged, not thrown to the caller.
    func indexMeeting(meetingID: UUID, segments: [MeetingSegment]) async {
        guard !segments.isEmpty else { return }
        do {
            try await MeetingRAGEngine.shared.index(meetingID: meetingID, segments: segments)
            await MainActor.run {
                NotificationCenter.default.post(name: .meetingRAGIndexingCompleted, object: meetingID)
            }
        } catch {
            Logger.error("Meeting RAG indexing failed (\(meetingID)): \(error)", subsystem: .transcription)
        }
    }

    // MARK: - Q&A

    /// Ask a question about a meeting. Uses Wax semantic retrieval when
    /// an index is available; falls back to the first 4000 chars of the
    /// full transcript when it isn't.
    func ask(question: String, meetingID: UUID, segments: [MeetingSegment]) async -> RAGAnswer {
        guard !question.isEmpty else {
            return RAGAnswer(text: "Please enter a question.", sources: [], usedRAG: false)
        }

        let (llm, loaded) = await MainActor.run {
            (AppState.shared.llmPostProcessor, AppState.shared.llmPostProcessor?.isModelLoaded ?? false)
        }
        guard let llm, loaded else {
            return RAGAnswer(
                text: "No AI model is loaded. Load one in Settings → AI Modes to use Ask AI.",
                sources: [], usedRAG: false
            )
        }

        // --- Retrieval ---
        let chunks: [RAGChunk]
        let usedRAG: Bool

        if MeetingRAGEngine.shared.isIndexed(meetingID),
           let retrieved = try? await MeetingRAGEngine.shared.retrieve(
               question: question, meetingID: meetingID, limit: 8),
           !retrieved.isEmpty {
            chunks  = retrieved
            usedRAG = true
        } else {
            chunks  = []
            usedRAG = false
        }

        // --- Context assembly ---
        let context: String
        if usedRAG {
            context = chunks.map { chunk in
                "[\(chunk.formattedStart)] \(chunk.speakersLabel): \(chunk.text)"
            }.joined(separator: "\n\n")
        } else {
            // Fallback: first 4000 chars of the full transcript
            let full = segments.map { "[\(formatSeconds($0.timestamp))] \($0.speakerName): \($0.text)" }
                               .joined(separator: "\n")
            context = String(full.prefix(4000))
        }

        let systemPrompt = """
        You are a meeting assistant. Answer the user's question using ONLY the meeting transcript context provided below.
        Be concise and direct. Reference specific speakers and timestamps (e.g. "at 10:23, Speaker 1 said…") when it adds clarity.
        If the answer is not in the context, say so honestly.

        TRANSCRIPT CONTEXT:
        \(context)
        """

        do {
            let answer = try await llm.process(
                text:           question,
                systemPrompt:   systemPrompt,
                userMessage:    question,
                temperature:    0.3,
                maxTokensCap:   512
            )
            return RAGAnswer(
                text:     answer.trimmingCharacters(in: .whitespacesAndNewlines),
                sources:  chunks,
                usedRAG:  usedRAG
            )
        } catch {
            Logger.error("Meeting Q&A failed: \(error)", subsystem: .transcription)
            return RAGAnswer(text: "Sorry, I couldn't answer that. Please try again.", sources: [], usedRAG: false)
        }
    }

    // MARK: - Title generation

    /// Names an untitled recording from its content. Run before `generateOverview`
    /// so the library row gets a real name within a couple of seconds instead of
    /// waiting out the full summary pass. No-op once the user has titled it.
    func generateTitle(segments: [MeetingSegment], meetingID: UUID, currentTitle: String) async {
        guard Self.isAutoGeneratedTitle(currentTitle) else {
            Logger.info("Meeting title: skipped — \"\(currentTitle)\" was set by the user", subsystem: .transcription)
            return
        }
        let transcript = Self.plainTranscript(segments)
        guard transcript.count >= 40 else { return }

        let (llm, loaded) = await MainActor.run {
            (AppState.shared.llmPostProcessor, AppState.shared.llmPostProcessor?.isModelLoaded ?? false)
        }
        guard let llm, loaded else {
            Logger.warning("Meeting title: skipped — no LLM loaded", subsystem: .transcription)
            return
        }

        let systemPrompt = """
        You name voice recordings. Read the transcript and reply with a title for it.

        RULES:
        1. Reply with the title and nothing else. No quotes, no label, no explanation, no trailing period.
        2. Between 3 and 7 words, on one line.
        3. Name the actual subject matter. "Google AI course breakdown" is a good title. "Recording", "Meeting notes" and "Transcript" say nothing — never use them.
        4. Do not begin with "Summary of", "Notes on", "Discussion about" or "A recording of".
        5. Write the title in the language of the transcript.
        6. Never use the characters < or >.
        """

        // Head plus tail: the opening states the subject and the closing usually
        // states the conclusion. The middle rarely changes what to call it.
        let excerpt = Self.headAndTail(transcript, headChars: 1600, tailChars: 500)

        do {
            let raw = try await llm.process(
                text:                   excerpt,
                systemPrompt:           systemPrompt,
                userMessage:            excerpt,
                temperature:            0.2,
                repetitionPenalty:      1.1,
                maxTokensCap:           48,
                outputTokensHint:       32,
                timeoutSecondsOverride: 25,
                throwOnFallback:        true
            )
            guard let title = Self.sanitizeTitle(raw) else {
                Logger.warning("Meeting title: unusable LLM output \"\(raw.prefix(80))\"", subsystem: .transcription)
                return
            }
            await MeetingManager.shared.updateTitle(meetingID: meetingID, title: title)
            // The detail header caches the title in @State, so it needs telling.
            await MainActor.run {
                NotificationCenter.default.post(
                    name: .meetingTitleDidGenerate, object: meetingID, userInfo: ["title": title]
                )
            }
            Logger.info("Meeting title: named \(meetingID) \"\(title)\"", subsystem: .transcription)
        } catch {
            Logger.error("Meeting title: generation failed: \(error.localizedDescription)", subsystem: .transcription)
        }
    }

    // MARK: - Overview generation

    func generateOverview(segments: [MeetingSegment], meetingID: UUID) async {
        let transcript = Self.timestampedTranscript(segments)
        Logger.info("Meeting overview: starting for \(meetingID), transcript=\(transcript.count) chars", subsystem: .transcription)
        guard !transcript.isEmpty else {
            Logger.warning("Meeting overview: skipped — transcript is empty", subsystem: .transcription)
            await MainActor.run { NotificationCenter.default.post(name: .meetingOverviewDidFail, object: meetingID) }
            return
        }
        let (llm, loaded) = await MainActor.run {
            (AppState.shared.llmPostProcessor, AppState.shared.llmPostProcessor?.isModelLoaded ?? false)
        }
        guard let llm, loaded else {
            Logger.warning("Meeting overview: skipped — no LLM loaded", subsystem: .transcription)
            await MainActor.run { NotificationCenter.default.post(name: .meetingOverviewDidFail, object: meetingID) }
            return
        }
        Logger.info("Meeting overview: LLM ready, starting generation", subsystem: .transcription)

        // A voice memo of a few sentences has nothing to structure — asking for the
        // full label set only makes the model invent decisions and owners.
        let wordCount = Self.plainTranscript(segments).split(whereSeparator: { $0 == " " || $0.isNewline }).count
        let isNote = wordCount < 60

        let systemPrompt = isNote ? Self.notePrompt : Self.overviewPrompt
        let userMessage = "TRANSCRIPT:\n\(transcript)"

        let raw: String
        do {
            raw = try await llm.process(
                text:                   transcript,
                systemPrompt:           systemPrompt,
                userMessage:            userMessage,
                temperature:            0.15,
                repetitionPenalty:      1.15,
                maxTokensCap:           2048,
                outputTokensHint:       isNote ? 200 : 1200,
                timeoutSecondsOverride: isNote ? 30 : 120,
                throwOnFallback:        true
            )
        } catch {
            Logger.error("Meeting overview: LLM generation failed: \(error.localizedDescription)", subsystem: .transcription)
            await MainActor.run { NotificationCenter.default.post(name: .meetingOverviewDidFail, object: meetingID) }
            return
        }

        Logger.info("Meeting overview: LLM produced \(raw.count) chars", subsystem: .transcription)

        guard var summary = MeetingOverviewParser.parse(raw) else {
            Logger.warning("Meeting overview: parse failed (no OVERVIEW line). Raw: \(raw.prefix(300))", subsystem: .transcription)
            await MainActor.run { NotificationCenter.default.post(name: .meetingOverviewDidFail, object: meetingID) }
            return
        }

        Logger.info("Meeting overview: parsed successfully — overview=\(summary.overview.prefix(80))…", subsystem: .transcription)
        summary.generatedAt = Date()
        await MeetingManager.shared.updateAISummary(meetingID: meetingID, summary: summary)
        Logger.info("Meeting overview: saved to CoreData for \(meetingID)", subsystem: .transcription)
        // Must post on main thread — onReceive handlers mutate @State
        await MainActor.run {
            NotificationCenter.default.post(name: .meetingOverviewDidGenerate, object: meetingID)
        }
    }

    // MARK: - Prompts

    /// Full-length summary. The bulk of the prompt is about OVERVIEW because that
    /// is what the user reads — the earlier "2-4 sentences" instruction produced
    /// summaries that said a topic was discussed without saying what was said.
    private static let overviewPrompt = """
    You summarize voice recordings. The input is a speech-to-text transcript, so it contains filler words, false starts and misheard words. Summarize what was meant, not the exact wording.

    Every transcript line begins with a marker like [95s] giving the number of seconds from the start. Copy those numbers into the seconds fields below. Never put a marker inside the OVERVIEW.

    OUTPUT FORMAT — each label on its own line, in this order. Emit a label only when the recording actually contains that thing.

    OVERVIEW: the summary
    TOPIC: short phrase | seconds
    DECISION: short label | what was decided | seconds
    OPEN: a question that was raised and never answered | seconds
    NEXT: when and where the next session is
    ACTION: the task | the person's name | the due date

    HOW TO WRITE THE OVERVIEW — this is the part that matters:
    - 250 to 350 words, as 2 to 4 paragraphs separated by a blank line. Write the label OVERVIEW: once, at the start; every paragraph after it belongs to it.
    - Do not stop after three sentences. A reader who never heard the recording must finish the OVERVIEW knowing the actual content.
    - Follow the order of the recording.
    - Keep the specifics: names, numbers, tools, definitions, comparisons and examples that were given.
    - State the point that was made, not that a point was made. Write "machine learning is a subfield of AI in the way thermodynamics is a subfield of physics" — not "the speaker explained how machine learning relates to AI".
    - Do not open with "In this recording", "The speaker discusses" or "This transcript". Start with the substance.
    - Plain sentences only inside the OVERVIEW. No bullets, no markdown, no headings.

    THE OTHER LABELS:
    - TOPIC: 3 to 6 lines, one per section of the recording, in the order they occur.
    - DECISION, OPEN, NEXT and ACTION apply to real discussions. A lecture, a video or a solo note usually has none of them, and leaving them out is the correct answer. Never invent a decision, an owner or a due date to fill the format.
    - ACTION requires a real person named in the transcript. If nobody was named, write no ACTION line.

    ALWAYS:
    - Write every line in the language of the transcript.
    - Never state anything the transcript does not say.
    - Never use the characters < or >.
    """

    /// Very short recordings — one line out, nothing to structure.
    private static let notePrompt = """
    You summarize short voice notes. Reply with exactly one line:

    OVERVIEW: two or three sentences saying what the note is about

    RULES:
    1. Keep every specific detail from the note — names, numbers, places, tasks.
    2. Write no other label. No TOPIC, no DECISION, no ACTION.
    3. No markdown, no bullets, no quotes.
    4. Never state anything the note does not say.
    5. Write in the language of the note.
    6. Never use the characters < or >.
    """

    // MARK: - Auto-generated titles

    /// Titles produced by the app itself, which the LLM may replace. Anything the
    /// user typed is left alone. Kept in sync with `defaultNoteTitle()` in the
    /// meeting UI and the provider display names in `MeetingDetector`.
    private static let autoTitleAppNames: Set<String> = [
        "zoom", "microsoft teams", "webex", "facetime", "google meet",
        "google hangouts", "whereby", "around", "slack huddle", "slack"
    ]

    nonisolated static func isAutoGeneratedTitle(_ title: String) -> Bool {
        let trimmed = title.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty { return true }
        if trimmed.hasPrefix("Note ") || trimmed.hasPrefix("Meeting ") { return true }
        return autoTitleAppNames.contains(trimmed.lowercased())
    }

    // MARK: - Private helpers

    private func formatSeconds(_ seconds: Double) -> String {
        let s = Int(seconds)
        return String(format: "%d:%02d", s / 60, s % 60)
    }

    /// Transcript with a seconds marker per line. Without it the model has no
    /// timestamps to cite and fabricates the seconds fields in TOPIC/DECISION/OPEN.
    private static func timestampedTranscript(_ segments: [MeetingSegment]) -> String {
        segments
            .filter { !$0.text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
            .map { "[\(Int($0.timestamp))s] \($0.speakerName): \($0.text)" }
            .joined(separator: "\n")
    }

    private static func plainTranscript(_ segments: [MeetingSegment]) -> String {
        segments.map { $0.text }
            .joined(separator: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private static func headAndTail(_ text: String, headChars: Int, tailChars: Int) -> String {
        guard text.count > headChars + tailChars else { return text }
        return String(text.prefix(headChars)) + "\n…\n" + String(text.suffix(tailChars))
    }

    /// First usable line of the model's reply, stripped of the decorations small
    /// on-device models add (labels, quotes, trailing punctuation).
    private static func sanitizeTitle(_ raw: String) -> String? {
        guard var line = raw
            .components(separatedBy: "\n")
            .map({ $0.trimmingCharacters(in: .whitespaces) })
            .first(where: { !$0.isEmpty })
        else { return nil }

        for label in ["TITLE:", "Title:", "OVERVIEW:"] where line.hasPrefix(label) {
            line = String(line.dropFirst(label.count))
        }
        line = line.trimmingCharacters(in: CharacterSet(charactersIn: " \t\"'“”«»<>*#.-–—"))
        line = line.replacingOccurrences(of: "<", with: "")
                   .replacingOccurrences(of: ">", with: "")
                   .trimmingCharacters(in: .whitespaces)

        guard line.count >= 3 else { return nil }
        guard !isAutoGeneratedTitle(line) else { return nil }
        return line.count > 70 ? String(line.prefix(70)).trimmingCharacters(in: .whitespaces) : line
    }
}
