//
//  DailyQuotes.swift
//  Whisperer
//
//  Daily inspirational quotes about voice, capture, and thinking
//

import Foundation

enum DailyQuotes {
    static let quotes = [
        "Your voice carries what your fingers forget to type.",
        "The best ideas don't wait for you to find a keyboard.",
        "Speaking your thoughts out loud is the first act of making them real.",
        "A word spoken is a thought that chose to exist.",
        "Clarity begins the moment you stop typing and start talking.",
        "Your voice is faster than your doubts.",
        "Every great idea was first a whisper.",
        "The gap between thinking and doing is often just a spoken sentence.",
        "Capture the thought before the silence takes it back.",
        "Wisdom doesn't wait for you to sit down — speak it while it's alive.",
        "Voice is memory that doesn't fade.",
        "The moment you speak it, it becomes more than a thought.",
        "Ideas are shy. Coax them out with your voice.",
        "What you say out loud, you begin to believe.",
        "Silence holds potential. Speech turns it into action.",
        "Your voice knows what your hands are too slow to write.",
        "Speak first. Edit later.",
        "The most powerful shortcut is your own voice.",
        "Words in the air can change the ground beneath you.",
        "When you whisper an idea, the world leans in.",
        "Don't let a great thought vanish into the noise of the day.",
        "Your spoken word is the seed of every written work.",
        "The fastest path from idea to action passes through your voice.",
        "Capture it now. Refine it later. But capture it.",
        "Speaking makes the invisible visible.",
        "Every note you capture is a future problem solved.",
        "Thought is noise until voice gives it shape.",
        "The sentence you speak today may be the breakthrough of tomorrow.",
        "Friction kills ideas. Your voice removes the friction.",
        "Don't wait for the right moment. Speak and create it.",
        "Voice is the most natural interface ever invented.",
        "What you say aloud, you own.",
        "Good thinking deserves to be heard, even just by you.",
        "Capture the moment — your future self will thank you.",
        "A spoken thought is a promise to yourself.",
        "The mind moves fast. Your voice can keep up.",
        "Don't let the best thought you had today go unrecorded.",
        "Listening to yourself is the beginning of understanding.",
        "Clarity doesn't come from thinking more — it comes from saying it out loud.",
        "Your voice is the pen that never runs out of ink.",
        "The thought you almost forgot was probably the most important one.",
        "Ideas don't wait. Neither should you.",
        "Speak it into existence, then make it so.",
        "The best journal entry is the one you actually make.",
        "Your voice leaves traces that your memory cannot.",
        "Every word spoken is a step toward your next big thing.",
        "Capture it rough. Perfection is for later.",
        "The cost of not capturing a great idea is higher than you think.",
        "Thought lives in the moment. Voice gives it permanence.",
        "Speak more. Forget less.",
        "Your voice is never wrong about what you truly feel.",
        "Speaking a problem aloud is the first step to solving it.",
        "You don't need better ideas. You need to capture the ones you already have.",
        "The whisper that becomes a note becomes a plan becomes a life.",
        "Every great conversation starts with a single spoken thought.",
        "Don't let the moment pass in silence.",
        "Voice removes the distance between mind and page.",
        "Capture the fleeting. Build the lasting.",
        "Your next idea is worth more than your phone screen.",
        "Words spoken with intention carry intention forward.",
        "The more you capture, the more you create.",
        "Speak today. Build tomorrow.",
        "The best meetings happen in your head. Capture them.",
        "Noise becomes signal the moment you speak it clearly.",
        "Thinking out loud is not a weakness — it's a superpower.",
        "Your voice is the original productivity tool.",
        "Don't let your best ideas stay trapped inside.",
        "A recorded thought is a promise to your future self.",
        "Speaking slowly is thinking quickly.",
        "One captured thought a day compounds into a life's work.",
        "The quieter the moment, the louder the insight.",
        "Speak it to believe it. Believe it to build it.",
        "Thought is fast. Memory is slow. Voice is the bridge.",
        "Your mind at 7am is worth capturing. Don't waste it.",
        "The best notes are the ones you never planned to take.",
        "Voice is honesty without the edit.",
        "Speak the rough draft. Perfect it at your desk.",
        "Every insight you lose is a lesson deferred.",
        "Your spoken word is more authentic than any typed draft.",
        "The shortest distance between two ideas is your voice.",
        "Capture what matters. Ignore the rest.",
        "Speaking makes thinking tangible.",
        "The note you almost didn't take is often the most valuable.",
        "Speak. Capture. Act. Repeat.",
        "Good ideas deserve more than a mental note.",
        "Your voice cuts through the fog that typing cannot.",
        "Moments of insight are rare. Treat them accordingly.",
        "Your voice is always within reach. Use it.",
        "The mind forgets, but the recording remembers.",
        "Speak it before it fades.",
        "Three seconds of voice can save three hours of rethinking.",
        "You don't need permission to think out loud.",
        "Voice gives weight to the weightless.",
        "Ideas spoken aloud grow bigger. Keep them.",
        "The best habit is the one that takes less than ten seconds.",
        "Speak it. The rest will follow.",
        "Your morning thoughts are gold. Mine them.",
        "Every transcription is a thread in a larger tapestry.",
        "Capture the spark before the wind takes it.",
        "The sentence you mutter to yourself might be the one that changes everything.",
        "Speaking your intention is the first act of commitment.",
        "Your voice tells the truth faster than your keyboard.",
        "The whisper today becomes the declaration tomorrow.",
        "Don't think about capturing. Just capture.",
        "A voice note is a gift from your present self to your future self.",
        "The thought that interrupts you might be trying to tell you something important.",
        "Say it now. Refine it forever.",
        "Your voice is available 24 hours a day. Use it generously.",
        "The loudest ideas are often the quietest whispers.",
        "Creativity doesn't ask for a clean desk — just an open mic.",
        "One voice note can unlock a week of clarity.",
        "Your ideas deserve to outlive the moment they appeared.",
        "The act of speaking transforms thinking.",
        "Capture the wandering thought before it vanishes.",
        "Words spoken with care become ideas handled with care.",
        "Don't hoard your thoughts. Speak them and set them free.",
        "Your voice is the most human technology you have.",
        "Speak what you know. Discover what you don't.",
        "The thought you say out loud is the thought you'll act on.",
        "Articulation is the first form of action.",
        "Your voice note collection is a record of your thinking evolution.",
        "Don't edit before you speak. Speak, then edit.",
        "Thinking is private. Speaking turns thought into something shared.",
        "A captured thought is potential energy. An uncaptured one is just loss.",
        "Your voice doesn't judge. It just captures.",
        "The habit of capture is the habit of progress.",
        "Speak into the void. Whisperer will catch it.",
        "Every note is a conversation with your future self.",
        "The best brain dump happens at the speed of speech.",
        "When in doubt, say it out loud.",
        "Language is the tool that shapes all other tools.",
        "You are always one voice note away from a breakthrough.",
        "Capture generously. Curate carefully.",
        "Voice is intimacy with your own thinking.",
        "The quiet walk holds more insight than the busy meeting.",
        "Speak what exists only in your mind — and make it permanent.",
        "Your unspoken ideas are your greatest untapped resource.",
        "Say the imperfect thing. Fix it later.",
        "The mind at rest speaks loudest. Listen.",
        "Every whisper is a vote for clarity.",
        "Momentum begins with a single word.",
        "Your voice can move faster than the thought that's chasing you.",
        "What you capture today becomes what you build tomorrow.",
        "Capture the raw. Refine the rare.",
        "Your voice is the bridge between thinking and doing.",
        "Great work often begins in a low voice.",
        "Don't lose the thread. Speak it.",
        "The best note-taker is the one who never has to try.",
        "You are always thinking. Start capturing.",
        "Voice is the rawest form of thought.",
        "Speak early. Speak often. Capture always.",
        "Your idea is not obvious to anyone else. Preserve it.",
        "The act of speaking is the act of deciding.",
        "Effortless capture makes room for effortless thinking.",
        "A voice note in traffic beats silence at a desk.",
        "The best productivity tool fits in your pocket and speaks your language.",
        "Whisper now. Shout later.",
        "Speaking is the shortcut to understanding yourself.",
        "Your voice holds the tone that your text loses.",
        "A captured moment can rewrite the future.",
        "Speak first. The structure will find itself.",
        "Your best insights come at inconvenient times. Capture them anyway.",
        "You think at the speed of life. Capture at the speed of voice.",
        "Don't wait to journal. Just speak.",
        "The voice note you're hesitating on is probably the most important one.",
        "Words are the atoms of every plan you'll ever execute.",
        "Your internal monologue deserves an audience — even if just a future you.",
        "Nothing clarifies like hearing yourself say it.",
        "Thinking out loud is not indulgence — it's craft.",
        "The idea you captured at midnight might run your morning meeting.",
        "Speak to understand. Then speak again to be understood.",
        "Your voice is the one tool that improves with use.",
        "The thought that breaks through silence is worth keeping.",
        "Ideas are promiscuous — they leave if you don't capture them.",
        "A single captured thought can carry a week forward.",
        "Whispering to yourself is the beginning of wisdom.",
        "Talk to yourself like your best ideas are listening.",
        "The idea is the easy part. Remembering it is the work.",
        "Your voice note today is your document tomorrow.",
        "Speak the version that's almost right. Capture will do the rest.",
        "Not all great things start with planning. Some start mid-sentence.",
        "Your voice is your most personal search engine.",
        "The thought you almost said is often the most honest one.",
        "Capture today. Decide tomorrow. Build forever.",
        "Voice is speed without sacrifice.",
        "Half the battle of execution is knowing what you want. Say it.",
        "Speak when the idea is warm. It will cool on the page.",
        "Your voice is never too far from your next great idea.",
        "Talk now. Write never. Let technology bridge the gap.",
        "The best writing starts as spoken thought.",
        "Capture the impulse. It might be the whole plan.",
        "Words you dare to say are the ones that move things forward.",
        "Your voice is always one tap away.",
        "You've lost a thousand ideas to memory. Start capturing.",
        "The spoken draft is the honest draft.",
        "Don't filter before you speak. Filter after you listen.",
        "Every creative block breaks when you start talking.",
        "Your shower ideas are your best ideas. Capture them.",
        "Voice captures what pen and paper cannot — the moment itself.",
        "Speaking a half-formed idea is braver than waiting for the perfect one.",
        "The voice that hesitates loses the thought.",
        "Speak like no one is listening. Your ideas will thank you.",
        "Your imagination is unlimited. Capture its output.",
        "The spoken word leaves an echo. The unspoken one leaves regret.",
        "Clarity arrives when you say it and hear it back.",
        "The best systems make it effortless to capture what matters.",
        "A great idea spoken is a great idea that has a chance.",
        "Never lose a thought to the friction of not having a pen.",
        "Speak now. Transcription is instant. Regret is not.",
        "Your voice turns the invisible into the inevitable.",
        "The walk, the commute, the pause — all prime time for speaking ideas.",
        "A single voice note can unlock the next 90 days.",
        "Don't let the best version of your thinking live only in your head.",
        "Whisper to the app. Let the app carry the weight.",
        "Language is the only code that writes itself.",
        "Your voice note is the beginning of your first draft.",
        "The idea you speak today might define the project of tomorrow.",
        "Great thinkers think out loud. Start there.",
        "Saying it makes it real. Capturing it makes it actionable.",
        "Trust your voice. The idea inside is worth hearing.",
        "The fastest note is the one you speak.",
        "Your voice is the most direct line between mind and world.",
        "Speak your intention into the day.",
        "The thought you almost texted — speak it instead.",
        "There is no draft too rough to be captured.",
        "Your ideas are more organized than you think. Say them.",
        "Capture the moment and the momentum.",
        "Speaking to yourself is the most productive meeting of your day.",
        "Voice note first. App later. The idea is what matters.",
        "The ideas you speak in private become the breakthroughs you share in public.",
        "Capture the chaos. Clarity comes in the listening.",
        "You are always a few words away from your next breakthrough.",
        "The spoken word is the original note-taking.",
        "Build the habit of speaking. The ideas will build themselves.",
        "Voice is the shortest path between two points: now and done.",
        "The quietest voice sometimes carries the loudest idea.",
        "The idea you said to nobody was still worth saying.",
        "One voice note before bed can change the morning.",
        "You don't need a clean room to have a clear thought. Just speak.",
        "Voice is the UI for the mind.",
        "Capture everything. The good stuff will reveal itself.",
        "Speaking creates a trail. Follow it.",
        "Every voice note is a breadcrumb back to your best thinking.",
        "The thought that surfaces mid-run — capture it before your heart rate drops.",
        "Your voice is the real-time record of who you're becoming.",
        "Speak what you know. Capture what you find.",
        "Voice is the format that forgets nothing.",
        "The idea that woke you up at 3am — that's the one worth capturing.",
        "Capture everything your mind tries to set aside.",
        "Speaking gives your thoughts a fighting chance.",
        "A voice note is an act of respect for your own thinking.",
        "The thought that made you smile in traffic? That one. Keep it.",
        "Your voice is a resource that renews itself every moment.",
        "Great ideas don't knock twice. Be ready.",
        "Capture your thinking at its peak.",
        "The habit of capturing is the habit of becoming.",
        "Voice note now. Read it and be surprised later.",
        "Your best self speaks clearly. Capture what it says.",
        "The quiet moment on the train is the loudest one for ideas.",
        "Speak like your ideas matter. Because they do.",
        "Capture without judgment. That's the first rule.",
        "Voice is the most underused channel we have.",
        "Your thought is complete the moment you speak it aloud.",
        "The pause before a meeting is full of ideas. Use it.",
        "Every sentence you capture is a sentence you don't have to rebuild.",
        "Speaking your values daily is the fastest way to live them.",
        "Whisper the idea. Build the world.",
        "The captured idea has infinite patience for your timing.",
        "Your voice is the one tool you always have with you.",
        "Speak, capture, repeat — the creative's flywheel.",
        "Your voice note collection is the autobiography of your thinking.",
        "The walk that cleared your head — that's where the ideas are.",
        "Before you open a blank document, speak into Whisperer.",
        "The rawest ideas are often the most useful.",
        "Your voice holds the frequency of your deepest thinking.",
        "Capture it now. It will make sense later.",
        "Speaking without an audience is still speaking. Do it.",
        "Your inner voice is brilliant. Give it a microphone.",
        "The commute is not lost time. It's capture time.",
        "Speak your priorities and watch them become real.",
        "The idea you almost let go — that's usually the one.",
        "Voice is free. Ideas are priceless. Use one to keep the other.",
        "Capture the edge of the thought, not just the center.",
        "Speaking is the act of taking your thinking seriously.",
        "Your voice at its most unguarded is at its most honest.",
        "Talk to Whisperer the way you talk to yourself at your best.",
        "The unrecorded idea is the most expensive thing you'll ever lose.",
        "Capture in motion. Edit in stillness.",
        "Speak the fragment. The whole will come.",
        "Your voice is the original productivity stack.",
        "Ideas flow when the friction disappears. This is that.",
        "Speak more than you think you should. You'll use more than you expect.",
        "The lightest tool is the most used tool. Voice qualifies.",
        "Let your voice lead. Your hands will follow.",
        "Talk through the hard problem. The answer lives in the speaking.",
        "Your voice note from last week might solve today's problem.",
        "Don't hold the thought. Release it. Capture it. Return to it.",
        "Your voice is a time capsule. Speak and seal.",
        "Speaking out loud is the act of deciding to move forward.",
        "The thought you saved yourself from forgetting — that was the right call.",
        "Speak the 80%. Capture will carry the 100%.",
        "Your voice holds the tense, the tone, the true feeling.",
        "Every captured word is a brick in something you haven't built yet.",
        "Begin with voice. Arrive at vision.",
        "The way you speak to yourself shapes the way you act in the world.",
        "Ideas often arrive as feelings. Voice translates them.",
        "The best creative act of the day might be a 30-second voice note.",
        "Speak. The transcript is waiting. The idea is ready.",
        "Your subconscious speaks. Give it a way to be heard.",
        "Capture now. You don't need context. You need the words.",
        "Your voice is the one tool that works while everything else fails.",
        "The sentence that came to you in the middle of something else — that's the one.",
        "Thinking is for the mind. Capture is for the future.",
        "Speak imperfectly and improve forever.",
        "The most useful word you said today might not have felt useful at the time.",
        "Your voice note is the first draft of your future work.",
        "Speaking your goals gives them gravity.",
        "Let the idea be clumsy. Capture it anyway.",
        "Voice is precision that feels like freedom.",
        "Capture the urgent. Revisit the important.",
        "The spoken thought travels from mind to world faster than any keyboard.",
        "Your voice note archive is the most honest record of who you are.",
        "You think more than you realize. Start capturing how much.",
        "Speak your next chapter into existence.",
        "The mind wanders on purpose. Follow it with your voice.",
        "Your voice is always available for the next great idea.",
        "Talk more to yourself. Listen more to what you say.",
        "Capture without censoring. Edit without mercy.",
        "The thought between two thoughts is often the most valuable one.",
        "Your voice can hold an idea until you're ready to act on it.",
        "Say it now. Future you will know what to do with it.",
        "Capture is the only guarantee that a good idea survives.",
        "Your voice holds the version of the idea that typing would change.",
        "Speaking is remembering in advance.",
        "The most valuable words you'll say today might be the quietest.",
        "Voice is the interface your brain was designed for.",
        "Speak the big idea before the small tasks consume you.",
        "Your next great project might be one voice note away.",
        "The thought that repeats itself is asking to be captured.",
        "Speaking makes your thinking accountable.",
        "A voice note is a contract with the idea you just had.",
        "Capture what excites you. Build what matters.",
        "Your voice is the pen that writes faster than thought.",
        "Every day you don't capture is a day you give away.",
        "The thought at the edge of language — reach for it with your voice.",
        "Speaking is the fastest way to know what you actually think.",
        "Capture the idea whole. Trim it later.",
        "Your voice is the most direct path to your own intelligence.",
        "The moment you speak it, it's no longer just yours — it's possible.",
        "Voice doesn't require perfect conditions. Neither should your ideas.",
        "The thought you captured on a walk might run your next strategy.",
        "Speak your priorities out loud. You'll know immediately if they're true.",
        "The record of your voice is the record of your growth.",
        "Capture the edges where the best ideas live.",
        "Your voice is the one tool that never runs out of battery.",
        "Speaking it out loud is the most radical thing you can do for an idea.",
        "Whisper now. The world will hear it when you're ready.",
        "You already have the ideas. Now start keeping them.",
        "Every voice note is proof that you showed up for your thinking today.",
        "Speak until you surprise yourself. Then capture that.",
        "Your voice note habit is your most underrated competitive advantage.",
        "The year's best idea is somewhere in this year's voice notes.",
        "Speak more than you planned. You'll use more than you expected.",
        "Today's whisper is tomorrow's milestone.",
        "A year of capturing your voice is a year of becoming who you meant to be.",
    ]

    /// Returns a random quote
    static var random: String {
        quotes.randomElement() ?? quotes[0]
    }
}
