//
//  GoldenSet.swift
//  WhispererTests
//
//  Reference transcripts for accuracy tests, generated by scripts/build-golden-set.py.
//

import Foundation

/// A full-file decode of one recording by the shipping model.
struct GoldenEntry: Decodable {
    let id: String
    let durationSec: Double
    let audioPath: String
    /// What the app produced and saved to history at the time — streaming output.
    let storedTranscript: String
    /// What the same model produces given the whole file at once.
    let goldenTranscript: String
    let language: String
    let modelUsed: String
}

/// The reference corpus for every streaming accuracy test.
///
/// **Why not `fixture.transcript`.** That field is `ZTRANSCRIPTION` — the app's own stored output,
/// which is streaming output: VAD-chunked, seam-stitched, and subject to precisely the defects
/// these tests exist to detect. Scoring a streaming run against a streaming reference is
/// circular in two directions at once. A real fix can read as a regression, because the fixed
/// output now disagrees with a reference that contains the bug; and a defect shared by both
/// cancels out and reads as nothing at all. The very first four recordings decoded for this set
/// showed the problem plainly: history had `"Why doesn't work?"` where the model, given the whole
/// file, says `"Why it doesn't work?"` — a word the streaming path dropped, sitting in the
/// reference as though it were correct.
///
/// **What this is instead.** A decode of the same audio by the same model with the same decoding
/// params, differing only in that nothing is windowed. It is deliberately *not* human ground
/// truth and must not be described as such: where the model mishears a word it will mishear it
/// here too, identically. That is the useful property. Model error is held constant on both sides
/// of the comparison, so the WER delta against this reference isolates the damage windowing does
/// — chunk seams, dropped boundary audio, duplicated commits — which is the thing under test.
///
/// **When to regenerate.** After adding recordings (the script is incremental), and after any
/// change to `WhisperBridge.makeFullParams`, which the script's `DECODE_ARGS` mirror. It is
/// checked in so a test run does not depend on a 20-minute decode, and it is reproducible:
/// greedy at `temperature = 0` with no fallback ladder yields the same bytes every time.
enum GoldenSet {

    private(set) static var entries: [String: GoldenEntry] = load()

    /// Golden reference for a fixture, or `nil` when that recording is not in the set — a
    /// recording added since the last regeneration, or one that decoded to silence. Callers
    /// should skip such fixtures rather than fall back to `fixture.transcript`: a corpus where
    /// some rows are scored against a clean reference and others against streaming output
    /// produces a mean that means nothing.
    static func reference(for fixtureID: String) -> String? {
        entries[fixtureID.uppercased()]?.goldenTranscript
    }

    static var isEmpty: Bool { entries.isEmpty }

    private static func load() -> [String: GoldenEntry] {
        guard let data = locate().flatMap({ try? Data(contentsOf: $0) }) else { return [:] }
        struct File: Decodable { let entries: [GoldenEntry] }
        guard let file = try? JSONDecoder().decode(File.self, from: data) else { return [:] }
        return Dictionary(uniqueKeysWithValues: file.entries.map { ($0.id.uppercased(), $0) })
    }

    /// Bundle first, then the source tree.
    ///
    /// The source-tree fallback is not belt and braces — whether `TestData/` is copied into the
    /// test bundle depends on Xcode's resource phase, and these tests are local-only regardless
    /// (they need the user's history database and a downloaded model on disk). Resolving against
    /// `#filePath` keeps the set readable when the bundle copy is absent, rather than silently
    /// degrading every accuracy assertion to "no reference, skipped".
    /// Which file the corpus was actually read from, for the benchmark report. A stale bundle
    /// copy and the checked-in source tree are indistinguishable from the numbers alone.
    static var resolvedSource: String {
        locate().map(\.path) ?? "<not found>"
    }

    private static func locate() -> URL? {
        if let url = Bundle(for: BundleToken.self).url(forResource: "golden-set", withExtension: "json") {
            return url
        }
        let source = URL(fileURLWithPath: #filePath)   // .../WhispererTests/Helpers/GoldenSet.swift
            .deletingLastPathComponent()               // .../WhispererTests/Helpers
            .deletingLastPathComponent()               // .../WhispererTests
            .appendingPathComponent("TestData/golden-set.json")
        return FileManager.default.fileExists(atPath: source.path) ? source : nil
    }

    private final class BundleToken {}
}
